version: 2

project_name: brinco

before:
  hooks:
    - go mod tidy

builds:
  - id: brinco
    main: ./cmd/brinco
    binary: brinco
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: brinco_archives
    builds:
      - brinco
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md

checksum:
  name_template: checksums.txt

signs:
  - id: checksums_minisign
    artifacts: checksum
    cmd: minisign
    signature: "${artifact}.minisig"
    args:
      - -S
      - -s
      - "{{ .Env.MINISIGN_SECRET_KEY_FILE }}"
      - -m
      - "${artifact}"
      - -x
      - "${signature}"
      - -t
      - "Brinco checksums signature"

release:
  github:
    owner: yerlinson10
    name: Brinco-CLI

nfpms:
  - id: brinco_linux_packages
    package_name: brinco
    homepage: https://github.com/yerlinson10/Brinco-CLI
    description: Chat CLI P2P en Go con salas y codigos de invitacion
    maintainer: Yerlinson <noreply@github.com>
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin

scoops:
  - name: brinco
    repository:
      owner: yerlinson10
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
      branch: main
    homepage: https://github.com/yerlinson10/Brinco-CLI
    description: Chat CLI P2P en Go con salas y codigos de invitacion
    commit_author:
      name: brinco-bot
      email: actions@github.com

